=== w3c/qtspecs/specifications/grammar-30/parser/applets/grammar.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--========================================================================
    DTD (Document Type Definition) for grammar definition originally created
    by James Clark.  The idea is to define an abstract grammar in XML than
    may then be used by documentation, directly by parser generators,
    or via an XSLT stylesheet or other transformation, may generate
    a parser compiler specification such as for YACC or JavaCC.

Norm and Scott moved this file, and added an explicit prefix, as part of the
transition toward a unified build process for last call and beyond. This involved
moving the location of the CVS repository, For earlier history information,
see /WWW/XML/Group/xpath-query-src/grammar.dtd

=========================================================================-->
<!-- The root element of the definition -->
<!ELEMENT g:grammar ((g:language)+, (g:start)+,
                   (g:exprProduction | g:production | g:exposition-production)+
				   , g:token*, (g:state-list)?)>
<!ATTLIST g:grammar
  xmlns:g CDATA #FIXED "http://www.w3.org/2001/03/XPath/grammar"
>

<!-- Declare a language subset or superset, if they are used in the
     if attributes.
     Attributes:
         id -> the id of the language. 'if' attributes should map to these ids.
         display-name -> The name to use for the descriptive name of the language.
-->
<!ELEMENT g:language EMPTY>
<!ATTLIST g:language
  id ID #REQUIRED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  display-name CDATA #REQUIRED
>

<!-- The grammar must say where the start point is.
     Attributes:
         name -> the name of the starting production.
         state -> the start state for lexical matching.
         if -> space separated list of tokens for conditional processing.
-->
<!ELEMENT g:start EMPTY>
<!ATTLIST g:start
  name IDREF #REQUIRED
  state CDATA #IMPLIED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
>

<!-- ============= Lexical Specifications (terminals) ==============-->
<!-- Define a token.
     Attributes:
         name -> the name of the token.
         if -> space separated list of tokens for conditional processing.
         inline -> tell if the BNF description should expand this token inline.
         is-macro -> "yes" if this token can be used just as a macro,
                     and not as a true token.
         value-type -> If just a grammatical token, use "none",
                       or use "string" for a string value
                       or use "number" for a number value
                       or use "id" if it is a token value with meaning.
-->
<!ELEMENT g:token (g:string | g:emph | g:zeroOrMore | g:charClass | g:char | g:optional | g:ref | g:xref | g:choice | g:oneOrMore | g:sequence | g:complement)*>
<!ATTLIST g:token
  name ID #REQUIRED
  exposition-name CDATA #IMPLIED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  inline CDATA #IMPLIED
  is-macro (yes | no) #IMPLIED
  is-xml (yes | no) #IMPLIED
  xhref CDATA #IMPLIED
  token-kind (skip) #IMPLIED
  value-type (none | string | number | id) #IMPLIED
  whitespace-spec (not-significant | significant | explicit) #IMPLIED
  node-type (void | string | StepExpr | FTUnaryNot | UnaryExpr) #IMPLIED
  show (yes | no) #IMPLIED
  delimiter-type (nondelimiting | delimiting | hide) #IMPLIED
  subtract-reg-expr CDATA #IMPLIED
  comment-id CDATA #IMPLIED
  xgc-id CDATA #IMPLIED
  exposition-only (no | yes) #IMPLIED
  needs-exposition-parens (no | yes) #IMPLIED
  is-local-to-terminal-symbol (no | yes) #IMPLIED
>

<!-- Specification of a single character token. -->
<!ELEMENT g:char (#PCDATA)>
<!ATTLIST g:char
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  complement (no | yes) #IMPLIED
  force-quote (single | double) #IMPLIED
>

<!-- SGML mode in emacs doesn't like this, so I'm avoiding it for now. -->
<!-- ATTLIST char
	xml:space CDATA #IMPLIED
-->

<!ELEMENT g:charClass (g:charCode | g:char | g:charCodeRange | g:charRange)+>
<!ATTLIST g:charClass
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
>
<!ELEMENT g:charCode EMPTY>
<!ATTLIST g:charCode
  value CDATA #REQUIRED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
>

<!ELEMENT g:charCodeRange EMPTY>
<!ATTLIST g:charCodeRange
  minValue CDATA #REQUIRED
  maxValue CDATA #REQUIRED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
>

<!ELEMENT g:charRange EMPTY>
<!ATTLIST g:charRange
  minChar (0 | A | a) #REQUIRED
  maxChar (0 | 9 | F | f | z | Z) #REQUIRED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
>

<!-- Defines a character that must be complemented by another character of
     the same value, such as a quote. -->
<!ELEMENT g:complement (g:charClass)>
<!ATTLIST g:complement
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
>

<!-- Defines a string token. -->
<!ELEMENT g:string (#PCDATA)>
<!ATTLIST g:string
  ignoreCase CDATA #IMPLIED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  show (yes | no) #IMPLIED
  token-user-action CDATA #IMPLIED
  process-value (no | yes) #IMPLIED
>

<!-- Talk to FS folks about what this is really supposed to mean.  -sb -->
<!ELEMENT g:emph (#PCDATA)>
<!ATTLIST g:emph
  ignoreCase CDATA #IMPLIED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
>


<!--=================== Lexical State Transitions =================== -->

<!ELEMENT g:state-list (g:state)+>
<!ATTLIST g:state-list
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
>

<!ELEMENT g:state (g:description?, g:transition+)>
<!ATTLIST g:state
  name ID #REQUIRED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  show (yes | no) #IMPLIED
>

<!ELEMENT g:tref EMPTY>
<!ATTLIST g:tref
  name IDREF #REQUIRED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  show (yes | no) #IMPLIED
>

<!ELEMENT g:description ANY>
<!ATTLIST g:description
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
>

<!-- Define a transition for a token or set of tokens.
     Attributes:
         refs -> IDREFS list of the tokens for which this transition applies.
         if -> space separated list of tokens for conditional processing.
               (Not currently used by the stylesheet!)
         nextState -> The next state to transition to. Invalid if popState us
                      used for the action.
         action -> State stack action.
-->
<!ELEMENT g:transition (g:description?, g:tref+)>
<!ATTLIST g:transition
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  next-state IDREF #IMPLIED
  action CDATA #IMPLIED
>

<!--=================== Parser Production Specifications ===============-->
<!-- A production that defines a "cascade" of productions that define
     operator precedence.
         name -> the ID of the production.
         if -> space separated list of tokens for conditional processing.
-->
<!ELEMENT g:exprProduction (g:level+)>
<!ATTLIST g:exprProduction
  name ID #REQUIRED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  node-type  (void | string | StepExpr | FTUnaryNot | UnaryExpr) #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT g:level (g:postfix | g:binary | g:prefix | g:primary)+>
<!ATTLIST g:level
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  node-type  (void | string | StepExpr | FTUnaryNot | UnaryExpr) #IMPLIED
  level-user-action CDATA #IMPLIED
>

<!-- Basic non-terminal production.
         name -> the ID of the production.
         if -> space separated list of tokens for conditional processing.
         show -> Don't show in the BNF if this value is "no".
-->
<!ELEMENT g:production (g:optional | g:ref |g:xref | g:choice | g:zeroOrMore | g:oneOrMore | g:string)+>
<!ATTLIST g:production
  name ID #REQUIRED
  exposition-name CDATA #IMPLIED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  show (yes | no) #IMPLIED
  node-type  (void | string | StepExpr | FTUnaryNot | UnaryExpr) #IMPLIED
  is-binary (no | yes) #IMPLIED
  whitespace-spec (not-significant | significant | explicit) #IMPLIED
  comment-id CDATA #IMPLIED
  xgc-id CDATA #IMPLIED
  condition CDATA #IMPLIED
  prod-user-action CDATA #IMPLIED
  xhref CDATA #IMPLIED
  is-xml (no | yes) #IMPLIED
  inline CDATA #IMPLIED
  value-type (none | string | number | id) #IMPLIED
  subtract-reg-expr CDATA #IMPLIED
>

<!ELEMENT g:exposition-production (g:optional | g:ref | g:xref | g:choice | g:sequence | g:zeroOrMore | g:oneOrMore | g:string)+>
<!ATTLIST g:exposition-production
  name CDATA #REQUIRED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  show (yes | no) #IMPLIED
  node-type CDATA #IMPLIED
  is-binary (no | yes) #IMPLIED
  whitespace-spec (not-significant | significant | explicit) #IMPLIED
  comment-id CDATA #IMPLIED
  xgc-id CDATA #IMPLIED
>

<!-- Defines a binary operator.
         name -> the ID of the production.
         if -> space separated list of tokens for conditional processing.
       Example:
       		<binary name="EqualityExpr">
				<choice>
					<ref name="Equals"/>
					<ref name="NotEquals"/>
				</choice>
			</binary>
-->
<!ELEMENT g:binary (g:ref | g:xref | g:choice | g:string | g:sequence)>
<!ATTLIST g:binary
  name ID #REQUIRED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  prefix-seq-type CDATA #IMPLIED
  condition CDATA #IMPLIED
  process-value (no | yes) #IMPLIED
>

<!ELEMENT g:postfix (g:ref | g:xref | g:optional | g:sequence | g:string)+>
<!ATTLIST g:postfix
  name ID #REQUIRED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  prefix-seq-type CDATA #IMPLIED
  condition CDATA #IMPLIED
  node-type  (void | string | StepExpr | FTUnaryNot | UnaryExpr) #IMPLIED
>

<!ELEMENT g:prefix (g:optional | g:ref | g:xref | g:choice | g:zeroOrMore | g:oneOrMore | g:sequence | g:next | g:string)+>
<!ATTLIST g:prefix
  name ID #REQUIRED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  prefix-seq-type CDATA "*"
  condition CDATA #IMPLIED
  node-type  (void | string | StepExpr | FTUnaryNot | UnaryExpr) #IMPLIED
>

<!-- This element is used in exprProduction to control where the next production
     will be called from.  If it is not used, the next production will automatically be
     called.
-->
<!ELEMENT g:next EMPTY>
<!ATTLIST g:next
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
>

<!ELEMENT g:primary (g:optional | g:ref | g:xref | g:choice |
                   g:zeroOrMore | g:oneOrMore | g:sequence | g:string)+>
<!ATTLIST g:primary
  name ID #REQUIRED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  condition CDATA #IMPLIED
  node-type  (void | string | StepExpr | FTUnaryNot | UnaryExpr) #IMPLIED
>

<!ELEMENT g:ref EMPTY>
<!ATTLIST g:ref
  name IDREF #REQUIRED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  unfold (no | yes) #IMPLIED
  orig IDREF #IMPLIED
  node-type  (void | string | StepExpr | FTUnaryNot | UnaryExpr) #IMPLIED
  show (no | yes) #IMPLIED
  exposition-only (no | yes) #IMPLIED
  needs-exposition-parens (no | yes) #IMPLIED
  token-user-action CDATA #IMPLIED
  nt-user-action-end CDATA #IMPLIED
  nt-user-action-start CDATA #IMPLIED
  subtract-reg-expr CDATA #IMPLIED
  lookahead CDATA #IMPLIED
>

<!ELEMENT g:xref EMPTY>
<!ATTLIST g:xref
  name CDATA #REQUIRED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  orig IDREF #IMPLIED
  node-type  (void | string | StepExpr | FTUnaryNot | UnaryExpr) #IMPLIED
  show (no | yes) #IMPLIED
  exposition-only (no | yes) #IMPLIED
  needs-exposition-parens (no | yes) #IMPLIED
>

<!--================ General Constructs =================-->
<!ELEMENT g:zeroOrMore (g:string | g:charClass | g:optional | g:ref | g:xref |
          g:choice | g:optional | g:zeroOrMore | g:oneOrMore | g:complement | g:string)+>
<!ATTLIST g:zeroOrMore
  name ID #IMPLIED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  subtract-reg-expr CDATA #IMPLIED
  lookahead CDATA #IMPLIED
>

<!ELEMENT g:oneOrMore (g:string | g:charClass | g:optional | g:ref | g:xref |
          g:choice | g:optional | g:zeroOrMore | g:oneOrMore | g:complement | g:string)+>
<!ATTLIST g:oneOrMore
  name ID #IMPLIED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  subtract-reg-expr CDATA #IMPLIED
  lookahead CDATA #IMPLIED
>

<!ELEMENT g:optional (g:string | g:charClass | g:optional | g:ref | g:xref |
          g:choice | g:optional | g:zeroOrMore | g:oneOrMore | g:sequence | g:complement | g:string)+>
<!ATTLIST g:optional
  name ID #IMPLIED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  lookahead CDATA #IMPLIED
>

<!-- Maybe should be divided into a choice-token, and choice? -->
<!ELEMENT g:choice (g:ref | g:xref | g:string | g:sequence | g:complement)+>
<!ATTLIST g:choice
  name ID #IMPLIED
  break CDATA #IMPLIED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  lookahead CDATA #IMPLIED
>

<!ELEMENT g:sequence (g:string | g:ref | g:xref | g:optional |
                    g:zeroOrMore | g:oneOrMore | g:choice |
                    g:next | g:char | g:string)+>
<!ATTLIST g:sequence
  name ID #IMPLIED
  if IDREFS #IMPLIED
  not-if IDREFS #IMPLIED
  lookahead CDATA #IMPLIED
>

=== w3c/qtspecs/specifications/grammar-30/xpath-grammar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2002 W3C(r) (http://www.w3.org/) (MIT (http://www.lcs.mit.edu/),
INRIA (http://www.inria.fr/), Keio (http://www.keio.ac.jp/)),
All Rights Reserved.
See http://www.w3.org/Consortium/Legal/ipr-notice-20000612#Copyright.
W3C liability
(http://www.w3.org/Consortium/Legal/ipr-notice-20000612#Legal_Disclaimer),
trademark
(http://www.w3.org/Consortium/Legal/ipr-notice-20000612#W3C_Trademarks),
document use
(http://www.w3.org/Consortium/Legal/copyright-documents-19990405),
and software licensing rules
(http://www.w3.org/Consortium/Legal/copyright-software-19980720)
apply.
-->
<!DOCTYPE g:grammar SYSTEM "grammar.dtd">

<g:grammar xmlns:g="http://www.w3.org/2001/03/XPath/grammar">
  <!-- ====================== Meta Information ==================== -->
  <!-- SJB grammar2spec.xsl seems to pick the first of these to create anchor names -->
  <g:language id="xpath1" display-name="XPath 1.0" if="xpath1"/>
  <g:language id="xpath20" display-name="XPath 2.0" if="xpath20"/>
  <g:language id="xpath30" display-name="XPath 3.0" if="xpath30"/>
  <g:language id="xpath31" display-name="XPath 3.1" if="xpath31"/>
  <g:language id="xquery10" display-name="XQuery 1.0" if="xquery10"/>
  <g:language id="xquery30" display-name="XQuery 3.0" if="xquery30"/>
  <g:language id="xquery31" display-name="XQuery 3.1" if="xquery31"/>
  <g:language id="xcore" display-name="XML Processing Formal Semantics Core Language 1.0" if="xcore"/>
  <g:language id="xslt2-patterns" display-name="XSLT 2.0 Patterns" if="xslt2-patterns"/>
  <g:language id="xslt30-patterns" display-name="XSLT 3.0 Patterns" if="xslt30-patterns"/>
  <!-- extensions: -->
  <g:language id="fulltext" display-name="XQuery Full-Text 1.0" if="fulltext"/>
  <g:language id="scripting" display-name="XQuery Scripting Extension 1.0" if="scripting"/>
  <g:language id="update10" display-name="XQuery Update Facility 1.0" if="update10"/>
  <g:language id="update30" display-name="XQuery Update Facility 3.0" if="update30"/>

  <!-- ====================== Entry Point Information ==================== -->
  <g:start name="ExprSingle" state="DEFAULT" if="xpath1"/>
  <g:start name="XPath" state="DEFAULT" if="xpath20 xpath30 xpath31"/>
  <g:start name="Expr" state="DEFAULT" if="xcore"/>
  <g:start name="QueryList" state="DEFAULT" if="xquery10 xquery30 xquery31"/>
  <g:start name="Pattern" state="DEFAULT" if="xslt2-patterns"/>
  <g:start name="Pattern30" state="DEFAULT" if="xslt30-patterns"/>

  <!-- ====================== Grammar Productions ==================== -->

  <!-- [ start XSLT 2.0 Patterns -->

  <g:production name="Pattern" if="xslt2-patterns">
    <g:ref name="PathPattern"/>
    <g:optional name="PathPatternTail">
      <g:string>|</g:string>
      <g:ref name="Pattern"/>
    </g:optional>
  </g:production>

  <g:production name="PathPattern" if="xslt2-patterns" xgc-id="leading-lone-slash">
    <g:choice break="true" name="PathPatternChoices">
      <g:sequence>
        <g:ref name="Slash"/>
        <g:optional name="OptionalRelativePathPattern" lookahead="1">
          <g:ref name="RelativePathPattern"/>
        </g:optional>
      </g:sequence>
      <g:sequence>
        <g:ref name="SlashSlash"/>
        <g:ref name="RelativePathPattern"/>
      </g:sequence>
      <g:sequence lookahead="2">
        <g:ref name="IdKeyPattern"/>
        <g:optional>
          <g:choice>
            <g:ref name="Slash" node-type="void"/>
            <g:ref name="SlashSlash"/>
          </g:choice>
          <g:ref name="RelativePathPattern"/>
        </g:optional>
      </g:sequence>
      <g:ref name="RelativePathPattern"/>
    </g:choice>
  </g:production>

  <g:production name="RelativePathPattern" if="xslt2-patterns" node-type="void">
    <g:ref name="PatternStep"/>
    <g:optional name="RelativePathPatternTail">
      <g:choice name="PatternStepSep">
        <g:ref name="Slash" node-type="void"/>
        <g:ref name="SlashSlash"/>
      </g:choice>
      <g:ref name="RelativePathPattern"/>
    </g:optional>
  </g:production>

  <g:production name="PatternStep" if="xslt2-patterns">
    <g:optional name="OptionalPatternAxis" lookahead="2">
      <g:ref name="PatternAxis"/>
    </g:optional>
    <g:ref name="NodeTest"/>
    <g:ref name="PredicateList"/>
  </g:production>

  <g:production name="PatternAxis" if="xslt2-patterns">
    <g:choice break="true" name="AxisChoice">
      <g:sequence>
        <g:string process-value="yes">child</g:string>
        <g:string>::</g:string>
      </g:sequence>
      <g:sequence>
        <g:string process-value="yes">attribute</g:string>
        <g:string>::</g:string>
      </g:sequence>
      <g:string>@</g:string>
    </g:choice>
  </g:production>

  <g:production name="IdKeyPattern" if="xslt2-patterns">
    <g:choice name="KeyOrIDPattern">
      <g:sequence>
        <g:string process-value="yes">id</g:string>
        <g:string>(</g:string>
        <g:ref name="IdValue"/>
        <g:string>)</g:string>
      </g:sequence>
      <g:sequence>
        <g:string process-value="yes">key</g:string>
        <g:string>(</g:string>
        <g:ref name="StringLiteral"/>
        <g:string>,</g:string>
        <g:ref name="KeyValue"/>
        <g:string>)</g:string>
      </g:sequence>
    </g:choice>
  </g:production>

  <g:production name="IdValue" node-type="void" if="xslt2-patterns">
    <g:choice>
      <g:ref name="StringLiteral"/>
      <g:ref name="VarRef"/>
    </g:choice>
  </g:production>

  <g:production name="KeyValue" node-type="void" if="xslt2-patterns">
    <g:choice>
      <g:ref name="Literal"/>
      <g:ref name="VarRef"/>
    </g:choice>
  </g:production>

  <!-- ] end XSLT 2.0 Patterns -->
  
  <!-- [ start XSLT 3.0 Patterns -->
  
  <g:production name="Pattern30" if="xslt30-patterns">
    <g:choice name="Pattern30Choices">
      <g:ref name="PredicatePattern"/>
      <g:ref name="UnionExprP"/>
    </g:choice> 
  </g:production>
  
  <g:production name="PredicatePattern" if="xslt30-patterns">
    <g:string>.</g:string>
    <g:ref name="PredicateList"/>
  </g:production>
  
  <g:production name="UnionExprP" if="xslt30-patterns">
    <g:ref name="IntersectExceptExprP"/>
    <g:zeroOrMore name="UnionExprPTail">
      <g:choice name="UnionExprPOperator">
        <g:string>union</g:string>
        <g:string>|</g:string>
      </g:choice>
      <g:ref name="IntersectExceptExprP"/>
    </g:zeroOrMore>
  </g:production>
  
  <g:production name="IntersectExceptExprP" if="xslt30-patterns">
    <g:ref name="PathExprP"/>
    <g:zeroOrMore name="IntersectExceptExprPTail">
      <g:choice name="IntersectExceptExprPOperator">
        <g:string>intersect</g:string>
        <g:string>except</g:string>
      </g:choice>
      <g:ref name="PathExprP"/>
    </g:zeroOrMore>
  </g:production>
  
  <g:production name="PathExprP" if="xslt30-patterns" xgc-id="leading-lone-slash">
    <g:choice break="true" name="PathExprPChoices">
      <g:ref name="RootedPath" lookahead="2"/>
      <g:sequence>
        <g:ref name="Slash"/>
        <g:optional name="OptionalRelativePathExprP" lookahead="1">
          <g:ref name="RelativePathExprP"/>
        </g:optional>
      </g:sequence>
      <g:sequence>
        <g:ref name="SlashSlash"/>
        <g:ref name="RelativePathExprP"/>
      </g:sequence>
      <g:ref name="RelativePathExprP"/>
    </g:choice>
  </g:production>
  
  <g:production name="RootedPath" if="xslt30-patterns">
    <g:choice name="VarOrFunctionCall">
      <g:ref name="VarRef"/>
      <g:ref name="FunctionCallP"/>
    </g:choice>
    <g:ref name="PredicateList"/>
    <g:optional>
      <g:choice name="RootedPathOperator">
        <g:ref name="Slash"/>
        <g:ref name="SlashSlash"/>
      </g:choice>
      <g:ref name="RelativePathExprP"/>
    </g:optional>
  </g:production>
  
  <g:production name="FunctionCallP" if="xslt30-patterns">
    <g:ref name="OuterFunctionName"/>
    <g:ref name="ArgumentListP"/>
  </g:production>
  
  <g:production name="OuterFunctionName" if="xslt30-patterns">
    <g:choice name="FNameChoice">
      <g:string process-value="yes">doc</g:string>
      <g:string process-value="yes">id</g:string>
      <g:string process-value="yes">element-with-id</g:string>
      <g:string process-value="yes">key</g:string>
      <g:ref name="URIQualifiedName"/>
    </g:choice>
  </g:production>

  <g:production name="ArgumentListP" if="xslt30-patterns">
    <g:string>(</g:string>
    <g:optional name="ArgListP">
      <g:ref name="ArgumentP"/>
      <g:zeroOrMore name="ArgListTailP">
        <g:string>,</g:string>
        <g:ref name="ArgumentP"/>
      </g:zeroOrMore>
    </g:optional>
    <g:string>)</g:string>
  </g:production>
  
  <g:production name="ArgumentP" if="xslt30-patterns">
    <g:choice name="ArgumentPChoice">
      <g:ref name="VarRef"/>
      <g:ref name="Literal"/>
    </g:choice>
  </g:production>
     
  <g:production name="RelativePathExprP" if="xslt30-patterns" node-type="void">
    <g:ref name="StepExprP"/>
    <g:zeroOrMore name="RelativePathExprPTail">
      <g:choice name="RelativePathExprPOperator">
        <g:ref name="Slash" node-type="void"/>
        <g:ref name="SlashSlash"/>
      </g:choice>
      <g:ref name="StepExprP"/>
    </g:zeroOrMore>
  </g:production>
  
  <g:production name="StepExprP" if="xslt30-patterns" >
    <g:choice name="StepExprPChoice">
      <g:ref name="PostfixExprP"/>
      <g:ref name="AxisStepP"/>
    </g:choice>
  </g:production>
  
  <g:production name="PostfixExprP" if="xslt30-patterns" >
    <g:ref name="ParenthesizedExprP"/>
    <g:ref name="PredicateList"/>
  </g:production>
  
  <g:production name="ParenthesizedExprP" if="xslt30-patterns" >
    <g:string>(</g:string>
    <g:ref name="UnionExprP"/>
    <g:string>)</g:string>
  </g:production>
  
  <g:production name="AxisStepP" if="xslt30-patterns" >
    <g:ref name="ForwardStepP"/>
    <g:ref name="PredicateList"/>
  </g:production>
